### ISSUE TITLE
Project roadmap

### ISSUE THREAD

**Issue by diegomura** [devongovett/textkit#2]
Hi @devongovett !
First of all, let me tell you how awesome I find this project. I played a bit with it today and I could make it work. The result was amazing. Inline styles, text hyphening, complex containers... just awesome.

I would like to use this eventually in [react-pdf](https://github.com/diegomura/react-pdf), and I would be more than happy to help in releasing a stable version of `textkit`. However, I would like to know the roadmap of this project, ask you some questions and share some thoughts. So here I go.

# Questions
- Is there any layout step you remember isn't working in some scenario? I saw that Bidi was commented. In general, what I would like to get is some idea of what's needed to do
- How do you plan to use this library? Is going to be used by `pdfkit` internally? If that's the case pdfkit api should change a bit right? Right now you call `.text` and that gets rendered straight into the document. If you plan to send several strings into an `AttributedString` I guess something has to change. This is extremely important for me because I need to know how I'll add this to my library 😄  

# Ideas
## Ability to plug custom engines
I think I saw it commented on the code somewhere, but it would be cool to have the ability to define custom `Trucation`, `Tabs`, `Justification`, `LineBreak` engines. If none are passed, you just use the ones in here. 

```js
let l = new LayoutEngine({
  justificationEngine: MyCustomEngine,
  // and so on.
});
```

For that we should provide with a valid interface for each case, which I don't know if it's possible to do in a neat way. But this will enable to support TeX line breaking, for example. 

## Public API
I know this isn't ready yet, but in the example you have to import several objects to make `LayoutEngine` work: `AttributedString`, `Container`, `TabStop`. Thinking on the future public API, I think it would be better to just export `LayoutEngine` (and maybe `Path` to create containers?). Any idea on how you see this being used in the future?

**Comment by devongovett** [comment]
Awesome, glad that this could potentially be a starting point for you. Sorry that the code is so scattered - it's really an unfinished project. I think I might have a few more things uncommitted on another machine so when I get back home from my current trip I'll commit them.

To answer your questions:

1. Yeah, Bidi is not implemented at the moment. I had started working on it at one point but was unhappy with the code. There might be another JS implementation of the bidi algorithm out there now - or I could commit what I did somewhere and we could clean it up maybe. My main issue is that I just don't have a lot of time.

    Other stuff that needs to be done in order to launch a stable version of this: tests - lots of them 😉. Sorry about that. Some parts of the code need a lot of clean up as well. Otherwise, it actually has quite a few features already.

2. For integration with PDFKit, the current example doesn't actually render text at all just the glyph paths directly. This isn't accessible (i.e. copy/paste won't work). Currently PDFKit requires a string to render text, and has its own internal text layout algorithm. What we really want is a way to pass a font + glyph ids + positions from textkit to PDFKit and have it render those exact glyphs in the exact positions provided. I had started working on this, and I think its in the uncommitted changes I mentioned earlier. I'll commit those soon.

    I don't think PDFKit will use textkit internally - it is quite a large library and not all PDFKit users will need it. I think it is a higher level library that should integrate with PDFKit but not be required. Also, textkit could be useable with other output formats than just PDF - you could swap out the `TextRenderer` with an implementation that drew to canvas or SVG maybe. The rest of textkit has nothing to do with PDFs at all.

As for the public interface for textkit, there are a lot of collaborating objects in the system. It's designed in a way similar to MVC - there are models (container, attributed string, etc.) , "views" (i.e. TextRenderer), and controllers (the layout engines). Ideally all of this would be overridable as you describe via dependency injection. The default implementations would be exported so you could extend them. And if you're just using the defaults, we still need to export them so you can set things up like AttributedStrings, Containers, etc.

All that is to say, I think we just export everything. Then you could import like `import {AttributedString, Container, LayoutEngine} from 'textkit'` and do your thing with it.

If you're interested, I'll give you access to the repo and we can work together on finishing this up. I don't have a whole lot of time to devote to it, but I can certainly help guide you and review things.

**Comment by diegomura** [comment]
Thanks @devongovett !
Sorry I've been a bit busy lately too 😅 

I would keep bidi for a second stage, and work on polishing the code (I have to admit that was a bit overwhelming and didn't want to change much when I read it) and being able to actually render text using pdfkit. I guess for that, we will also have to extend pdfkit functionality? I'll see.

And of course, writing tests haha. I'll try to isolate as much testable cases as I can 😄 

First, I want to feel comfortable with the code, or course.
Btw, I will not merge anything without your consent, unless you really want to. 
I'll start working slowly into this because I don't have much time too haha. But I really want to move forward with this.

Thanks!
