### ISSUE TITLE
Make project monorepo

### ISSUE THREAD

**Issue by diegomura** [devongovett/textkit#25]
Hi @devongovett !
I know you have been busy. Just wanted to know what do you think about this.
I currently have trouble to use this lib both on client & server. And the main reason (at least for the moment) is for the `font-manager` dependency, which works only on node. 

We now support dependency injection (and I created my own font substitution engine), but `font-manager` is installed anywhere when you install textkit.

So I thought of making this project a monorepo, in which the core will be one package, and then each engine a separate one. It's the final step to make this truly pluggable. Also, it's great for separating concerns, making each package self-contained.

Would like to know what you think before doing it!

**Comment by devongovett** [comment]
So what would you get by default when you just install `textkit`? Would you need to install each piece manually even if you're using the default implementation? That seems like it might be hard to use.

**Comment by diegomura** [comment]
No. We make the `textkit` export what currently does, but what actually does internally is importing all pieces and binding them together. By this, you can both get textkit ready to use, and also a `textkit/core` you can use independently and inject your custom config without depending on any breaking specific dependency

**Comment by devongovett** [comment]
ah ok, makes sense to me
